<?xml version="1.0"?>
<package format="3">
  <name>status_interfaces</name>
  <version>0.0.0</version>
  <description>ROS2 custom message interface for system status</description>
  <maintainer email="anan@todo.todo">anan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <depend>builtin_interfaces</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
